---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - PASSWORD=Hackaton2021@MEGAG #optional
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=Hackaton2021@MEGAG #optional
#      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.hackatonbbva.g-cs.dev #optional
    volumes:
      - /path/to/appdata/config:/config
      - /root:/root
    ports:
      - 8443:8443
    restart: unless-stopped