version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ws.address=:8090"
      - "--entrypoints.wss.address=:8091"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=roblesmgustavoj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog.filepath=/access.log"
      - "--accesslog.bufferingsize=100"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8085"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
      - "8085:8085"
      - "8090:8090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/access.log:/access.log"

  backend:
    build : .
    restart: always
    container_name: backend
    user: root
    environment:
      - TZ= America/Mexico_City
      - REDIS_URL=redis
    volumes:
      - ./app:/code/app
    ports:
      - "8080:80"
    depends_on:
     - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`hackatonbbva.g-cs.dev`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backendService.loadbalancer.server.port=80"

  redis:
    image: redis:latest
    container_name: cache
    

  httpd:
      container_name: frontend
      ports:
          - '9000:80'
      volumes:
          - '../FrontEnd/dist:/usr/local/apache2/htdocs/'
      image: 'httpd:2.4'
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=(Host(`frontend.hackatonbbva.g-cs.dev`))"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.services.frontendService.loadbalancer.server.port=80"


