version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=roblesmgustavoj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog.filepath=/access.log"
      - "--accesslog.bufferingsize=100"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8085"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
      - "8085:8085"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/access.log:/access.log"

  backend:
    build : .
    restart: always
    user: root
    environment:
      - TZ= America/Mexico_City
    volumes:
      - ./app:/code/app
    ports:
      - "82:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`hackatonbbva.g-cs.dev`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backendService.loadbalancer.server.port=82"

  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - PASSWORD=Hackaton2021@MEGAG #optional
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=Hackaton2021@MEGAG #optional
#      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.hackatonbbva.g-cs.dev #optional
    volumes:
      - ./vscode/config:/config
      - /root/Hackaton2021/:/hackaton/
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=(Host(`code.hackatonbbva.g-cs.dev`))"
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls.certresolver=myresolver"
      - "traefik.http.services.codeService.loadbalancer.server.port=8443"

